project:
  type: website
  preview:
    host: 0.0.0.0
    port: 6411
format:
  revealjs:
    progress: false
    slide-number: true
    mermaid:
      theme: dark
    theme:
      - default
      - themes/custom.scss

