%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '23px'}}}%%
block-beta
    columns 25
    block:lr_access:25
        id1("Access Layer")
    end
    block:lr_core:25
        id2("Core Layer")
    end
    block:lr_res:25
        id3("Resources Layer")
    end

    style id1 fill:#fe4f51,stroke-width:0px
    style lr_access fill:#fe4f51, stroke-width:0px
    style id2 fill:#fec701,stroke-width:0px
    style lr_core fill:#fec701, stroke-width:0px
    style id3 fill:#5dca36,stroke-width:0px
    style lr_res fill:#5dca36, stroke-width:0px

